#pragma once

#include "CoreMinimal.h"

UENUM()
enum class EKeyboardInputs : uint8
{
	WinButton		UMETA(DisplayName = "Windows"),
	LeftAlt			UMETA(DisplayName = "Left Alt"),
	LeftControl		UMETA(DisplayName = "Left Control"),
	LeftShift		UMETA(DisplayName = "Left Shift"),
	Tab				UMETA(DisplayName = "Tab"),
	Enter			UMETA(DisplayName = "Enter"),
	Space			UMETA(DisplayName = "Space"),
	ESC				UMETA(DisplayName = "Escape"),
	Delete			UMETA(DisplayName = "Delete"),
	Backspace		UMETA(DisplayName = "Backspace"),
	CapsLock		UMETA(DisplayName = "Caps Lock"),
	Zero_Key		UMETA(DisplayName = "0"),
	One_Key			UMETA(DisplayName = "1"),
	Two_Key			UMETA(DisplayName = "2"),
	Three_Key		UMETA(DisplayName = "3"),
	Four_Key		UMETA(DisplayName = "4"),
	Five_Key		UMETA(DisplayName = "5"),
	Six_Key			UMETA(DisplayName = "6"),
	Seven_Key		UMETA(DisplayName = "7"),
	Eight_Key		UMETA(DisplayName = "8"),
	Nine_Key		UMETA(DisplayName = "9"),
	A_Key			UMETA(DisplayName = "A"),
	B_Key			UMETA(DisplayName = "B"),
	C_Key			UMETA(DisplayName = "C"),
	TR_C_Key		UMETA(DisplayName = "Ç"),
	D_Key			UMETA(DisplayName = "D"),
	E_Key			UMETA(DisplayName = "E"),
	F_Key			UMETA(DisplayName = "F"),
	G_Key			UMETA(DisplayName = "G"),
	TR_G_Key		UMETA(DisplayName = "Ğ"),
	H_Key			UMETA(DisplayName = "H"),
	I_Key			UMETA(DisplayName = "I"),
	TR_I_Key		UMETA(DisplayName = "İ"),
	J_Key			UMETA(DisplayName = "J"),
	K_Key			UMETA(DisplayName = "K"),
	L_Key			UMETA(DisplayName = "L"),
	M_Key			UMETA(DisplayName = "M"),
	N_Key			UMETA(DisplayName = "N"),
	O_Key			UMETA(DisplayName = "O"),
	TR_O_Key		UMETA(DisplayName = "Ö"),
	P_Key			UMETA(DisplayName = "P"),
	Q_Key			UMETA(DisplayName = "Q"),
	R_Key			UMETA(DisplayName = "R"),
	S_Key			UMETA(DisplayName = "S"),
	TR_S_Key		UMETA(DisplayName = "Ş"),
	T_Key			UMETA(DisplayName = "T"),
	U_Key			UMETA(DisplayName = "U"),
	TR_U_Key		UMETA(DisplayName = "Ü"),
	V_Key			UMETA(DisplayName = "V"),
	W_Key			UMETA(DisplayName = "W"),
	X_Key			UMETA(DisplayName = "X"),
	Y_Key			UMETA(DisplayName = "Y"),
	Z_Key			UMETA(DisplayName = "Z"),
};
ENUM_CLASS_FLAGS(EKeyboardInputs)